### ISSUE TITLE
demo page is broken

### ISSUE THREAD

**Issue by yanfali** [nijikokun/bootstrap-notify#18]
http://nijikokun.github.io/bootstrap-notify/ the button to bring up a random alert no longer seems to work.

Here's a screenshot of the console in chrome:

![developer_tools_-_http___nijikokun github io_bootstrap-notify_](https://f.cloud.github.com/assets/2275667/1230467/068aa252-27dc-11e3-88c8-3d6d9d4703e1.png)

**Comment by nijikokun** [comment]
Fixed.
