### ISSUE TITLE
overlapping with other elements

### ISSUE THREAD

**Issue by max-favilli** [nijikokun/bootstrap-notify#6]
If on the same position I have some other elements, like bootstrap navbar "search box", the notification shows below these other elements.

I solved adding z-index:9999;

```
.notifications{position:fixed;z-index:9999;}
```

But I am not a css expert and I don't know if that is ok.

**Comment by nijikokun** [comment]
If all you did was add z-index, yes that is fine actually. I will update it later to reflect this.
